# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbs_db', '0003_imagefile_imageclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelinfo',
            name='challenge',
        ),
    ]
